name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: get branch
        run: |
          echo $GITHUB_HEAD_REF >> $GITHUB_OUTPUT
        id: get_branch
      - name: Check PR
        if: success() && steps.find-pr.outputs.pr
        run: echo ${{ steps.get_branch.outputs.branch }}
